
server:
  port: 8083


spring:
  application:
    name: ai-service

  Data:
    mongodb:
      url: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/